Transacionar Pix: Magento x Vindi
vindi/vindi-magento2 pull request #88
Opened 2022-02-14 15:52 UTC by dtharssis

## O que mudou
Campo para o cliente inserir o CPF ao selecionar o método de pagamento PIX.

## Motivação
Como nós vamos integrar um novo método de pagamento - Pix, precisamos permitir uma transação do tipo Pix. Uma regra desse método de pagamento é o CPF do cliente, que se não for enviado pela API será rejeitado ao tentar criar o pedido.

## Solução proposta
Adicionar o campo CPF ao selecionar o método de pagamento. Considerando possíveis temas de magento, o campo CPF foi adicionado como toggle, ou seja, é possível desativar essa funcionalidade no painel administrativo, caso o tema usado na loja já faça envio desse documento do cliente (CPF).

## Como testar
1. Acesse o painel administrativo e vá em Lojas -> Configurações -> Configuração -> Vendas -> Métodos de pagamento -> Outros métodos de pagamento.
    a. Habilite o documento (Por padrão, estará desabilitado)
        ![image](https://user-images.githubusercontent.com/14346775/153896378-6b1d5630-10c3-4886-b738-8c1afaa8017c.png)

2. Faço um pedido e vá até o checkout.
3. No checkout, ao selecionar o método de pagamento PIX, deverá aparecer o campo para o cliente informar o CPF.
    ![image](https://user-images.githubusercontent.com/14346775/153897682-e8237d41-a568-4537-a1e5-f59a49038a48.png)

## Riscos
Já existe uma feature criada, na qual essa é dependente. É necessário garantir que o merge dessa branch seja realizado após a branch https://github.com/trezoteam/vindi-magento2/tree/feature/pix

## Impactos negativos previstos
Não há. Essa funcionalidade se trata de uma nova feature

## Instruções para deploy
Esse feature é dependente da branch [feature/pix](https://github.com/trezoteam/vindi-magento2/tree/feature/pix)

2022-02-16 21:30 UTC, laerte-guimaraes commented
@dtharssis consegue atualizar essa branch com as últimas alterações da `master`?

Isso é sempre necessário para garantir que um código não sobrescreva o outro 😉

2022-02-16 21:44 UTC, laerte-guimaraes requested changes
Apenas um ponto de atenção !

![image](https://user-images.githubusercontent.com/31661772/154362377-3c790746-59d7-41d8-b513-adb13f4fe926.png)

A validação do CPF só deve ser exibida caso o mesmo seja inválido.
Caso esteja correto, não é necessário exibir o campo.

2022-02-17 16:51 UTC, dtharssis commented
> @dtharssis consegue atualizar essa branch com as últimas alterações da `master`?
> 
> Isso é sempre necessário para garantir que um código não sobrescreva o outro wink

É possível sim, é que eu tinha mandado essa antes das últimas atualizações. Mas vou acertar a questão do CPF válido e já deixo a branch atualizado =)

2022-02-17 19:37 UTC, laerte-guimaraes commented on view/frontend/web/js/view/payment/method-renderer/vindi-pix.js
> +                const message = !documentValidate.isValidCpf(this?.document?.value()) ? '' : 'CPF inválido';
Acredito que aqui o correto seja `''` se verdadeiro e `'CPF inválido'` se falso não? 🤔 
```suggestion
                const message = documentValidate.isValidCpf(this?.document?.value()) ? '' : 'CPF inválido';
```

2022-02-18 10:16 UTC, dtharssis commented on view/frontend/web/js/view/payment/method-renderer/vindi-pix.js
> +                const message = !documentValidate.isValidCpf(this?.document?.value()) ? '' : 'CPF inválido';
@laerte-guimaraes você está certo, obrigado por ver esse detalhe.

2022-02-21 17:28 UTC, laerte-guimaraes approved these changes

2022-02-21 18:52 UTC, LeoAraujo01 approved these changes

2022-02-21 20:22 UTC, merged